# Generated by Django 2.2.6 on 2019-10-20 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_topic_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['published'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
